### ISSUE TITLE
Adding Repository on Debian 10 fails

### ISSUE THREAD

**Issue by bepstein111** [alvistack/ansible-role-podman#1]
Received the following error when trying on Debian 10. After manually adding the repository via instructions found at [here](https://www.naemon.org/download/#repo_setup) (and substituting alvistack for naemon), molecule converge seems to have worked fine, and verify completes successfully.

`TASK [runc : apt-add-repository] ***********************************************
FAILED - RETRYING: apt-add-repository (3 retries left).
FAILED - RETRYING: apt-add-repository (2 retries left).
FAILED - RETRYING: apt-add-repository (1 retries left).
failed: [localhost] (item={'filename': 'home:alvistack', 'repo': 'deb http://download.opensuse.org/repositories/home:/alvistack/Debian_10/ /', 'state': 'present'}) => {"ansible_loop_var": "item", "attempts": 3, "changed": false, "item": {"filename": "home:alvistack", "repo": "deb http://download.opensuse.org/repositories/home:/alvistack/Debian_10/ /", "state": "present"}, "msg": "Failed to update apt cache: E:The repository 'https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/xUbuntu_10  Release' does not have a Release file."}

PLAY RECAP *********************************************************************
localhost                  : ok=5    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0`

**Comment by hswong3i** [comment]
First of all this Ansible Role no longer depend on Kubic repo, since it couldn't work well together with CRI-O and Kubernetes related official package. That's why I rework everything from sketch with https://build.opensuse.org/project/show/home:alvistack

Next, your repo path for Kubic is incorrect, too. It should be https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/Debian_10/ for Debian 10.

Finally, sorry I didn't keep maintain a good upgrade path for this Ansible Role, due to my limited man power. In order to install everything correctly:
* Check your `/etc/apt/sources.list` and `/etc/apt/sources.list.d/`, remove all legacy Kubic or AlviStack repo
* Re-run `apt-get update && apt -y full-upgrade` and verify if still any error message
* Confirm you are using the latest `master` (or even `develop`) branch of this Ansible Role
* Now re-run and verify the result ;-)
