### ISSUE TITLE
manual pages

### ISSUE THREAD

**Issue by hmoffatt** [alvistack/ansible-role-podman#15]
Is there another package I need to install to get manual pages, or can these be added? The original Debian packages have them (eg podman-run.1.gz, in package podman), and it would be helpful to have them in 4.3. THanks.

**Comment by hswong3i** [comment]
Ummm....... Another good question...

Short answer: no, I didn't provide manual page in the package, and no plan for it, yet.

Long answer: Sometime build the manual page require extra build dependency, e.g. md2man which I faced before. Sometime these docs related dependency couldn't provide by legacy OS (e.g. as old as CentOS 7 and Ubuntu 18.04 which still in my supported OS list). This lead me to manually packaging them for building the docs...

BTW, the installed manual page seems much less price-performance-ratio from today point of view, which most likely we could get the latest updated version with a simple googling...

Case similar for tests: upstream should already ensure the code quality for us, as an individual packager (but not official OS distribution maintainers) I don't hope to waste time for packaging tests related dependency...

So due to my laziness and limited man power, I skip both docs and tests during packaging :-(

**Comment by hmoffatt** [comment]
I understand. Thanks for the detailed reply. Fortunately the Podman command line help is also quite good.
