### ISSUE TITLE
how to install podman3 

### ISSUE THREAD

**Issue by zzguang520520** [alvistack/ansible-role-podman#19]
the version is the same as dnf install podman，I want to install podman3 on fedora 36/37，how to use ansible-role-podman to install podman3

**Comment by hswong3i** [comment]
This role now point to my pre-compiled pre-packaged rpm build by OBS:
* https://github.com/alvistack/ansible-role-podman/blob/master/vars/fedora-37.yml#L26
* https://github.com/alvistack/ansible-role-podman/blob/master/vars/fedora-37.yml#L38
* https://build.opensuse.org/package/show/home:alvistack/containers-podman-4.3.1
* https://download.opensuse.org/repositories/home:/alvistack/Fedora_37/x86_64/
* https://download.opensuse.org/repositories/home:/alvistack/Fedora_37/x86_64/podman-4.3.1-1.31.x86_64.rpm

Since I had already remove podman3 from my OBS repo, you couldn't use this role to install that, sorry.
