### ISSUE TITLE
Missing pasta executable

### ISSUE THREAD

**Issue by Hbbb** [alvistack/ansible-role-podman#24]
Hi, 

I'm setting up podman to run my containers through systemd. The command that actually runs is:
```bash
/usr/bin/podman run --name=systemd-trader-portal --cidfile=/run/user/1000/trader-portal.cid --replace --rm --cgroups=split --sdnotify=conmon -d 734485531948.dkr.ecr.us-east-1.amazonaws.com/trader-portal:main
```

When I run this command myself, I see the following error:
```bash
Error: could not find pasta, the network namespace can't be configured: exec: "pasta": executable file not found in $PATH
```

I'm not sure if this is something I'm supposed to install on my own, or if it should be provided by this role.

I'm new to ansible so apologies if this is a stupid question.

**Comment by hswong3i** [comment]
This is because alvistack.containers_common will handle `passt` install, see https://github.com/alvistack/ansible-role-containers_common/blob/master/vars/ubuntu-22.04.yml#L32

Moreover, you could refer to https://github.com/alvistack/ansible-role-podman/blob/master/ansible-galaxy-requirements.yml and https://github.com/alvistack/ansible-role-podman/blob/master/molecule/default/converge.yml for the exact Ansible dependency.
