### ISSUE TITLE
Needed to change role name `podman` to `alvistack.podman`

### ISSUE THREAD

**Issue by g3n35i5** [alvistack/ansible-role-podman#5]
This role is awesome but for the "quick start" i needed to change the role name `podman` to `alvistack.podman` in `molecule/default/converge.yml`. Is this an error or did I make a mistake?

**Comment by hswong3i** [comment]
Good question with some background history:
1. In the old bad day before Ansible Galaxy, install Ansible Role with GIT submodule looks much usable for me
2. During the early day with Ansible Galaxy, we are not enforced with FQCN as https://ansible-lint.readthedocs.io/en/latest/default_rules/#fqcn-builtins now a day
3. I didn't use any external Ansible Role across my ecosystem, so no FQCN with `alvistack.*` is required
4. Now a day Ansible Galaxy handle both Role and Collection (e.g. https://galaxy.ansible.com/alvistack/kube_master and https://galaxy.ansible.com/alvistack/kubernetes) so naming with FQCN looks much important.
5. As https://github.com/alvistack/ansible-role-podman/blob/master/.gitlab-ci.yml#L8-L12, I will symlink the Role as `$HOME/.ansible/roles/podman` before running CI with my self-hosted GitLab Runner

Anyway, thank you for your suggestion, and I will give some effort to update all of my Ansible Role / Collection / Docker / Vagrant with Ansible FQCN ;-)

**Comment by g3n35i5** [comment]
Ah, I see. Thanks for your quick reply :smile:

**Comment by hswong3i** [comment]
@g3n35i5 ok let see how its going on: https://github.com/alvistack/ansible-role-podman/commit/0b7641e3ba5e958cded57b843da7edb789b2efbc

**Comment by hswong3i** [comment]
@g3n35i5 finally it result as 150+ repo need update across the ecosystem~~~

Thank you very much for pushing this reasonable fix, which delay for quite a while due to my laziness :-(

**Comment by hswong3i** [comment]
@g3n35i5 some follow up issue for Ansible Collection: in case roles are managed as git submodule under Ansible Collection, it should be rename as "roles/podman" only without the namespace.

This is because Ansible Collection contents, e.g. plugin and module and roles, are already prefix with `alvistack.kubernetes.` so here podman become `alvistack.kubernetes.podman`.

Therefore we couldn't name it as `roles/alvistack.podman` else become `alvistack.kubernetes.alvistack.podman` and so invalid :-(
